# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYTQrzw4n6dTT3PZ44hCY9qsoNeg4k8d
"""

# ================================================================
# STREAMLIT APP - DASHBOARD STUNTING INDONESIA (SAFE GEO VERSION)
# ================================================================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import joblib, os, json, requests, re

# ======================= SETUP ================================
st.set_page_config(page_title="📊 Dashboard Stunting Indonesia", layout="wide")
st.title("🇮🇩 Dashboard Analisis Stunting Indonesia")
st.markdown("### *Clustering, Klasifikasi, dan Prediksi Stunting berbasis Data Sosial Ekonomi*")
st.markdown("---")

# ======================= LOAD DATA ================================
@st.cache_data
def load_data():
    df_ = pd.read_excel("DATA_SUM_STUNTING.xlsx")
    df_.columns = [c.strip() for c in df_.columns]
    return df_

df = load_data()

st.sidebar.subheader("📤 Upload Dataset Baru (Opsional)")
uploaded_file = st.sidebar.file_uploader("Pilih file Excel (.xlsx)", type=["xlsx"])
if uploaded_file:
    df = pd.read_excel(uploaded_file)
    st.sidebar.success("✅ Data berhasil dimuat dari file upload!")

# Pastikan kolom Provinsi ada
if "Provinsi" not in df.columns:
    st.error("❌ Kolom 'Provinsi' tidak ditemukan di dataset.")
    st.stop()

# ======================= LOAD MODEL ================================
@st.cache_resource
def load_models():
    cluster = joblib.load("models/cluster_model.pkl")
    clf = joblib.load("models/classification_model.pkl")
    reg = joblib.load("models/regression_model.pkl")
    with open("models/expected_features.json", "r", encoding="utf-8") as f:
        meta = json.load(f)
    return cluster, clf, reg, meta

cluster_model, clf_model, reg_model, expected = load_models()

# ======================= GEOJSON HANDLER ================================
PROV_COORDS = {
    "ACEH": (4.70, 96.75), "SUMATERA UTARA": (2.11, 99.55), "SUMATERA BARAT": (-0.74, 100.80),
    "RIAU": (0.29, 101.71), "KEPULAUAN RIAU": (0.92, 104.45), "JAMBI": (-1.61, 103.61),
    "SUMATERA SELATAN": (-3.32, 104.91), "BENGKULU": (-3.58, 102.35), "LAMPUNG": (-4.56, 105.41),
    "KEP. BANGKA BELITUNG": (-2.74, 106.44), "BANTEN": (-6.41, 106.06), "DKI JAKARTA": (-6.17, 106.83),
    "JAWA BARAT": (-6.89, 107.64), "JAWA TENGAH": (-7.15, 110.14), "D I YOGYAKARTA": (-7.79, 110.37),
    "JAWA TIMUR": (-7.54, 112.24), "BALI": (-8.34, 115.09), "NUSA TENGGARA BARAT": (-8.65, 117.36),
    "NUSA TENGGARA TIMUR": (-8.66, 121.08), "KALIMANTAN BARAT": (-0.13, 111.10), "KALIMANTAN TENGAH": (-1.68, 113.38),
    "KALIMANTAN SELATAN": (-3.09, 115.28), "KALIMANTAN TIMUR": (0.54, 116.42), "KALIMANTAN UTARA": (2.84, 117.39),
    "SULAWESI UTARA": (1.49, 124.84), "GORONTALO": (0.70, 122.45), "SULAWESI TENGAH": (-1.43, 121.45),
    "SULAWESI BARAT": (-2.84, 119.23), "SULAWESI SELATAN": (-3.67, 119.97), "SULAWESI TENGGARA": (-4.14, 122.17),
    "MALUKU": (-3.24, 130.15), "MALUKU UTARA": (1.57, 127.81), "PAPUA": (-4.27, 138.08),
    "PAPUA BARAT": (-1.34, 133.17), "PAPUA BARAT DAYA": (-0.88, 131.26),
    "PAPUA PEGUNUNGAN": (-4.10, 138.94), "PAPUA SELATAN": (-8.49, 140.40), "PAPUA TENGAH": (-3.36, 135.50)
}

# Fungsi untuk normalisasi nama provinsi agar cocok
def normalize_province(name):
    if pd.isna(name):
        return None
    name = str(name).upper().strip()
    name = re.sub(r"PROVINSI|PROPINSI|KAB\.?|KOTA|DAERAH ISTIMEWA", "", name)
    name = re.sub(r"[^A-Z\s]", "", name)
    name = name.replace("  ", " ").strip()
    return name

@st.cache_data
def load_geojson():
    urls = [
        "https://raw.githubusercontent.com/superpikar/indonesia-geojson/master/indonesia-prov.geojson",
        "https://raw.githubusercontent.com/superpikar/indonesia-geojson/master/indonesia-province.geojson"
    ]
    for url in urls:
        try:
            r = requests.get(url, timeout=10)
            r.raise_for_status()
            st.success(f"🌍 GeoJSON dimuat dari {url}")
            return r.json()
        except Exception:
            continue
    st.warning("❌ Tidak ada GeoJSON valid. Menggunakan titik koordinat manual.")
    return None

geojson = load_geojson()

# ======================= SAFE MAP PLOTTER ================================
def plot_map_safe(df_map, color_col, title, discrete=False, discrete_map=None):
    dfp = df_map.copy()
    dfp["Provinsi"] = dfp["Provinsi"].astype(str)
    dfp["prov_up"] = dfp["Provinsi"].map(normalize_province)

    # Tambahkan koordinat
    dfp["lat"] = dfp["prov_up"].map(lambda p: PROV_COORDS.get(p, (np.nan, np.nan))[0])
    dfp["lon"] = dfp["prov_up"].map(lambda p: PROV_COORDS.get(p, (np.nan, np.nan))[1])

    # Jika semua NaN → fallback titik acak aman
    if dfp["lat"].isna().all():
        st.warning("⚠️ Tidak ada lokasi cocok, menampilkan titik acak di Indonesia.")
        dfp["lat"] = np.random.uniform(-7, 2, size=len(dfp))
        dfp["lon"] = np.random.uniform(100, 125, size=len(dfp))

    dfp = dfp.dropna(subset=["lat", "lon"])

    if discrete:
        fig = px.scatter_geo(
            dfp, lat="lat", lon="lon", color=color_col,
            hover_name="Provinsi", color_discrete_map=discrete_map or {}, title=title
        )
    else:
        fig = px.scatter_geo(
            dfp, lat="lat", lon="lon", color=color_col,
            hover_name="Provinsi", color_continuous_scale="RdYlGn_r", title=title
        )

    fig.update_geos(fitbounds="locations", showcountries=True)
    st.plotly_chart(fig, use_container_width=True)

# ======================= MODE PILIHAN ================================
st.sidebar.title("📁 Pilih Fitur Analisis")
mode = st.sidebar.radio("Pilih mode:", ["🧭 Clustering", "🏥 Klasifikasi Kesehatan", "📈 Prediksi Stunting"])

# ======================= CLUSTERING ================================
if mode == "🧭 Clustering":
    st.subheader("🧭 Clustering Tingkat Kerentanan Stunting per Provinsi")
    try:
        X = df[expected.get("features_base", [])]
        cluster_labels = cluster_model.predict(X)
        df["Cluster"] = cluster_labels
        cluster_map = {0: "Sejahtera (Maju)", 1: "Sedang (Mainstream)", 2: "Rentan (Tertinggal)"}
        df["Kategori_Cluster"] = df["Cluster"].map(cluster_map)
        plot_map_safe(df, "Kategori_Cluster", "🗺️ Clustering Kerentanan Stunting",
                      discrete=True,
                      discrete_map={"Sejahtera (Maju)": "green", "Sedang (Mainstream)": "orange", "Rentan (Tertinggal)": "red"})
    except Exception as e:
        st.error(f"❌ Gagal menjalankan clustering: {e}")

# ======================= KLASIFIKASI ================================
elif mode == "🏥 Klasifikasi Kesehatan":
    st.subheader("🏥 Klasifikasi Daerah Sehat vs Tidak Sehat")
    try:
        X = df[expected.get("features_all", [])]
        y_pred = clf_model.predict(X)
        df["Prediksi_Sehat"] = np.where(y_pred == 1, "Sehat", "Tidak Sehat")
        plot_map_safe(df, "Prediksi_Sehat", "🗺️ Daerah Sehat vs Tidak Sehat",
                      discrete=True, discrete_map={"Sehat": "green", "Tidak Sehat": "red"})
    except Exception as e:
        st.error(f"❌ Gagal menjalankan klasifikasi: {e}")

# ======================= REGRESI ================================
else:
    st.subheader("📈 Prediksi Stunting Tahun Depan")
    try:
        X = df[expected.get("features_all", [])]
        y_pred = reg_model.predict(X)
        df["Prediksi_Stunting_TahunDepan"] = y_pred
        plot_map_safe(df, "Prediksi_Stunting_TahunDepan", "🗺️ Prediksi Stunting Tahun Depan (%)", discrete=False)
        st.dataframe(df[["Provinsi", "Prediksi_Stunting_TahunDepan"]].sort_values("Prediksi_Stunting_TahunDepan"))
    except Exception as e:
        st.error(f"❌ Gagal menjalankan prediksi: {e}")